# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/vivadoproject/vga_snake/vga_snake.srcs/sources_1/bd/vga_snake/ip/vga_snake_ilmb_v10_0/vga_snake_ilmb_v10_0.xci
# IP: The module: 'vga_snake_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivadoproject/vga_snake/vga_snake.srcs/sources_1/bd/vga_snake/ip/vga_snake_ilmb_v10_0/vga_snake_ilmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_snake_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/vivadoproject/vga_snake/vga_snake.srcs/sources_1/bd/vga_snake/ip/vga_snake_ilmb_v10_0/vga_snake_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_snake_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/vivadoproject/vga_snake/vga_snake.srcs/sources_1/bd/vga_snake/ip/vga_snake_ilmb_v10_0/vga_snake_ilmb_v10_0.xci
# IP: The module: 'vga_snake_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivadoproject/vga_snake/vga_snake.srcs/sources_1/bd/vga_snake/ip/vga_snake_ilmb_v10_0/vga_snake_ilmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_snake_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/vivadoproject/vga_snake/vga_snake.srcs/sources_1/bd/vga_snake/ip/vga_snake_ilmb_v10_0/vga_snake_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_snake_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
