# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/limlitdoc.xdc

# XDC: new/nexys_ddr4_vga.xdc

# Block Designs: bd/vga_snake/vga_snake.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_snake || ORIG_REF_NAME==vga_snake} -quiet] -quiet

# IP: bd/vga_snake/ip/vga_snake_microblaze_0_0/vga_snake_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_snake_microblaze_0_0 || ORIG_REF_NAME==vga_snake_microblaze_0_0} -quiet] -quiet

# IP: bd/vga_snake/ip/vga_snake_microblaze_0_axi_periph_0/vga_snake_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_snake_microblaze_0_axi_periph_0 || ORIG_REF_NAME==vga_snake_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/vga_snake/ip/vga_snake_microblaze_0_axi_intc_0/vga_snake_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_snake_microblaze_0_axi_intc_0 || ORIG_REF_NAME==vga_snake_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/vga_snake/ip/vga_snake_microblaze_0_xlconcat_0/vga_snake_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_snake_microblaze_0_xlconcat_0 || ORIG_REF_NAME==vga_snake_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/vga_snake/ip/vga_snake_mdm_1_0/vga_snake_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_snake_mdm_1_0 || ORIG_REF_NAME==vga_snake_mdm_1_0} -quiet] -quiet

# IP: bd/vga_snake/ip/vga_snake_clk_wiz_1_0/vga_snake_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_snake_clk_wiz_1_0 || ORIG_REF_NAME==vga_snake_clk_wiz_1_0} -quiet] -quiet

# IP: bd/vga_snake/ip/vga_snake_rst_clk_wiz_1_100M_0/vga_snake_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_snake_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==vga_snake_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/vga_snake/ip/vga_snake_axi_uartlite_0_0/vga_snake_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_snake_axi_uartlite_0_0 || ORIG_REF_NAME==vga_snake_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/vga_snake/ip/vga_snake_axi_gpio_0_0/vga_snake_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_snake_axi_gpio_0_0 || ORIG_REF_NAME==vga_snake_axi_gpio_0_0} -quiet] -quiet

# IP: bd/vga_snake/ip/vga_snake_xbar_0/vga_snake_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_snake_xbar_0 || ORIG_REF_NAME==vga_snake_xbar_0} -quiet] -quiet

# IP: bd/vga_snake/ip/vga_snake_dlmb_v10_0/vga_snake_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_snake_dlmb_v10_0 || ORIG_REF_NAME==vga_snake_dlmb_v10_0} -quiet] -quiet

# IP: bd/vga_snake/ip/vga_snake_ilmb_v10_0/vga_snake_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_snake_ilmb_v10_0 || ORIG_REF_NAME==vga_snake_ilmb_v10_0} -quiet] -quiet

# IP: bd/vga_snake/ip/vga_snake_dlmb_bram_if_cntlr_0/vga_snake_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_snake_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==vga_snake_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/vga_snake/ip/vga_snake_ilmb_bram_if_cntlr_0/vga_snake_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_snake_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==vga_snake_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/vga_snake/ip/vga_snake_lmb_bram_0/vga_snake_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_snake_lmb_bram_0 || ORIG_REF_NAME==vga_snake_lmb_bram_0} -quiet] -quiet

# IP: bd/vga_snake/ip/vga_snake_top_0_1/vga_snake_top_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_snake_top_0_1 || ORIG_REF_NAME==vga_snake_top_0_1} -quiet] -quiet

# IP: bd/vga_snake/ip/vga_snake_auto_pc_0/vga_snake_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_snake_auto_pc_0 || ORIG_REF_NAME==vga_snake_auto_pc_0} -quiet] -quiet

# XDC: bd/vga_snake/vga_snake_ooc.xdc
